version: "2"
services:
  app:
    container_name: backend-database
    build: .
    ports:
      - "3000:3000"
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
