apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app.kubernetes.io/name: node-express-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.image.tag }}
    app.kubernetes.io/component: mongo
    app.kubernetes.io/part-of: mongo
    app.kubernetes.io/managed-by: helm2
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: mongo
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongo
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: mongo
        image: mongo:{{ .Values.image.tag }}
        ports:
        - containerPort: 27017
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: 27017
          initialDelaySeconds: 1
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /
            port: 27017
          initialDelaySeconds: 1
          periodSeconds: 5
